spring.application.name=suiviprojet

spring.datasource.url=jdbc:mysql://localhost:3306/suivi_projet
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Afficher les requêtes SQL dans la console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#----------------------------------------------

# --- CONFIGURATION DE L'UPLOAD DE FICHIERS ---
# Taille maximale d'un seul fichier (ex: 10 Mo)
spring.servlet.multipart.max-file-size=10MB
# Taille maximale de toute la requête (ex: si on envoie plusieurs fichiers d'un coup)
spring.servlet.multipart.max-request-size=10MB

# Dossier où les fichiers seront physiquement stockés sur votre PC (à la racine du projet)
file.upload-dir=uploads/documents