spring.application.name=suiviprojet


spring.datasource.url=jdbc:mysql://localhost:3306/suivi_projet
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Afficher les requÃªtes SQL dans la console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#----------------------------------------------

# --- CONFIGURATION DE L'UPLOAD DE FICHIERS ---
# Taille maximale d'un seul fichier (ex: 10 Mo)
spring.servlet.multipart.max-file-size=10MB
# Taille maximale de toute la requÃªte (ex: si on envoie plusieurs fichiers d'un coup)
spring.servlet.multipart.max-request-size=10MB

# Dossier oÃ¹ les fichiers seront physiquement stockÃ©s sur votre PC (Ã  la racine du projet)
file.upload-dir=uploads/documents


#----------------------------------------------


# --- CONFIGURATION SECURITE JWT ---
# Une clé secrète complexe (minimum 256 bits). Ne la partagez jamais en production !
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Durée de validité du token en millisecondes (Ici : 24 heures = 86400000 ms)
jwt.expiration=86400000